# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Docker internal network
host    all             all             172.25.0.0/16           md5

# Local network (ajusta a tu red)
host    all             all             10.10.0.0/16            md5

# Localhost
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# Unix socket local
local   all             all                                     peer

